export const ErrorCodes = {
  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_PASSWORD_CHANGE_REQUIRED: 'AUTH_PASSWORD_CHANGE_REQUIRED',
  
  // Permissions & Tenant
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  TENANT_ACCESS_DENIED: 'TENANT_ACCESS_DENIED',
  
  // Resources
  ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
  BUILDING_NOT_FOUND: 'BUILDING_NOT_FOUND',
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',
  CONTRACT_NOT_FOUND: 'CONTRACT_NOT_FOUND',
  CONTRACT_EXPIRED: 'CONTRACT_EXPIRED',
  INVOICE_NOT_FOUND: 'INVOICE_NOT_FOUND',
  
  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;

export type ErrorCode = keyof typeof ErrorCodes;
