import * as fs from 'fs';
import * as path from 'path';
import * as yaml from 'yaml';
import * as crypto from 'crypto';

export function generateAllViews() {
    const gatesDir = path.resolve(__dirname, '../../docs/gates');
    const engineeringDir = path.resolve(__dirname, '../../docs/engineering');
    const docsDir = path.resolve(__dirname, '../../docs');
    
    if (!fs.existsSync(gatesDir)) return;
    
    const files = fs.readdirSync(gatesDir).filter(f => f.endsWith('_GATE.yaml'));
    const gates: any[] = [];
    
    for (const file of files) {
        const gate = yaml.parse(fs.readFileSync(path.join(gatesDir, file), 'utf8'));
        const epic = file.replace('EPIC_', '').replace('_GATE.yaml', '');
        gates.push({ epic, ...gate });
    }
    
    // 1. Dashboard
    const dashLines = [
        '# EOS Operator Dashboard',
        '',
        '> [!IMPORTANT]',
        '> This file is automatically generated by EOS v5 from Gate outputs. Do not edit manually.',
        '',
        '| Epic | Status | Decision | Evaluated At |',
        '|---|---|---|---|'
    ];
    for (const g of gates) {
        dashLines.push(`| ${g.epic} | ${g.status} | ${g.decision || '-'} | ${g.evaluatedAtUtc || '-'} |`);
    }
    const dashPath = path.join(engineeringDir, 'EOS_OPERATOR_DASHBOARD.md');
    fs.writeFileSync(dashPath, dashLines.join('\n'));
    
    // 2. Matrix
    const matrixLines = [
        '# Business Verification Matrix',
        '',
        '> [!IMPORTANT]',
        '> Automatically generated by EOS v5. Do not edit.',
        '',
        '| Epic | Implementation State |',
        '|---|---|'
    ];
    for (const g of gates) {
        matrixLines.push(`| ${g.epic} | ${g.epic_closed ? 'CLOSED' : 'OPEN'} |`);
    }
    const matrixPath = path.join(engineeringDir, 'BUSINESS_VERIFICATION_MATRIX.md');
    fs.writeFileSync(matrixPath, matrixLines.join('\n'));
    
    // 3. Roadmap
    const roadmapLines = [
        '# Master Execution Roadmap',
        '',
        '> [!IMPORTANT]',
        '> Automatically generated by EOS v5. Do not edit.',
        '',
        '| Stage | Status |',
        '|---|---|'
    ];
    for (const g of gates) {
        roadmapLines.push(`| Epic ${g.epic} | ${g.status} |`);
    }
    const roadmapPath = path.join(engineeringDir, 'MASTER_EXECUTION_ROADMAP.md');
    fs.writeFileSync(roadmapPath, roadmapLines.join('\n'));
    
    // 4. Score
    const scoreLines = [
        '# Production Scorecard',
        '',
        '> [!IMPORTANT]',
        '> Automatically generated by EOS v5. Do not edit.',
        '',
        `Total Verified Epics: ${gates.filter(g => g.epic_closed).length} / ${gates.length}`
    ];
    const scorePath = path.join(engineeringDir, 'PRODUCTION_SCORE.md');
    fs.writeFileSync(scorePath, scoreLines.join('\n'));
    
    // Record hashes to detect manual tampering
    const hashes: Record<string, string> = {
        'EOS_OPERATOR_DASHBOARD.md': crypto.createHash('sha256').update(fs.readFileSync(dashPath)).digest('hex'),
        'BUSINESS_VERIFICATION_MATRIX.md': crypto.createHash('sha256').update(fs.readFileSync(matrixPath)).digest('hex'),
        'MASTER_EXECUTION_ROADMAP.md': crypto.createHash('sha256').update(fs.readFileSync(roadmapPath)).digest('hex'),
        'PRODUCTION_SCORE.md': crypto.createHash('sha256').update(fs.readFileSync(scorePath)).digest('hex')
    };
    
    fs.writeFileSync(path.resolve(__dirname, '../../.eos/hashes.json'), JSON.stringify(hashes, null, 2));
}

export function detectTampering(): string {
    const hashFile = path.resolve(__dirname, '../../.eos/hashes.json');
    if (!fs.existsSync(hashFile)) return 'VALID'; // Not generated yet
    
    const engineeringDir = path.resolve(__dirname, '../../docs/engineering');
    const saved = JSON.parse(fs.readFileSync(hashFile, 'utf8'));
    
    const paths: Record<string, string> = {
        'EOS_OPERATOR_DASHBOARD.md': path.join(engineeringDir, 'EOS_OPERATOR_DASHBOARD.md'),
        'BUSINESS_VERIFICATION_MATRIX.md': path.join(engineeringDir, 'BUSINESS_VERIFICATION_MATRIX.md'),
        'MASTER_EXECUTION_ROADMAP.md': path.join(engineeringDir, 'MASTER_EXECUTION_ROADMAP.md'),
        'PRODUCTION_SCORE.md': path.join(engineeringDir, 'PRODUCTION_SCORE.md')
    };
    
    for (const [name, p] of Object.entries(paths)) {
        if (!fs.existsSync(p)) return 'MARKDOWN_TAMPERED';
        const currentHash = crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
        if (currentHash !== saved[name]) {
            return 'MARKDOWN_TAMPERED';
        }
    }
    
    return 'VALID';
}

if (require.main === module) {
    generateAllViews();
    console.log("All views generated.");
}
