import * as fs from 'fs';
import * as path from 'path';
import * as yaml from 'yaml';

export function generateDashboard() {
    const gatesDir = path.resolve(__dirname, '../../docs/gates');
    const dashboardPath = path.resolve(__dirname, '../../docs/engineering/EOS_OPERATOR_DASHBOARD.md');
    
    if (!fs.existsSync(gatesDir)) return;
    
    const files = fs.readdirSync(gatesDir).filter(f => f.endsWith('_GATE.yaml'));
    
    const mdLines = [
        '# EOS Operator Dashboard',
        '',
        '> [!IMPORTANT]',
        '> This file is automatically generated by EOS v4 from Gate outputs. Do not edit manually.',
        '',
        '| Epic | Status | Verified At |',
        '|---|---|---|'
    ];
    
    for (const file of files) {
        const gate = yaml.parse(fs.readFileSync(path.join(gatesDir, file), 'utf8'));
        const epic = file.replace('EPIC_', '').replace('_GATE.yaml', '');
        mdLines.push(\| \ | \ | \ |\);
    }
    
    fs.writeFileSync(dashboardPath, mdLines.join('\n'));
}

if (require.main === module) {
    generateDashboard();
    console.log("Dashboard generated.");
}
