@baseUrl = http://localhost:3001/api/v1
@loginEmail = admin@homeland.vn
@loginPassword = {{$dotenv E2E_ADMIN_PASSWORD}}
@authToken = {{login.response.body.accessToken}}

### Login to get token
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "emailOrPhone": "{{loginEmail}}",
  "password": "{{loginPassword}}"
}

### Get Dashboard
GET {{baseUrl}}/dashboard
Authorization: Bearer {{authToken}}
