(() => {
  'use strict';
  const {chapters,sources}=window.HOMELAND_LIFECYCLE;
  const $=id=>document.getElementById(id);
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const labels={code:'Có đường xử lý trong code',fixed:'Đã xử lý trong code',error:'Sai / xung đột đã thấy',gap:'Thiếu / chưa nối',review:'Cần xác minh thêm'};
  const unresolved=node=>node.issues.some(issue=>issue.kind!=='fixed');
  let current=chapters[0],selected=current.nodes[0],issuesOnly=false;
  const svgEl=(tag,attrs={},text)=>{const el=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const [k,v] of Object.entries(attrs))el.setAttribute(k,v);if(text!==undefined)el.textContent=text;return el;};
  function words(text,max=24){const out=[];let line='';for(const word of text.split(' ')){if((line+' '+word).trim().length>max&&line){out.push(line);line=word;}else line=(line+' '+word).trim();}if(line)out.push(line);return out;}
  function route(){let hash;try{hash=decodeURIComponent(location.hash.slice(1));}catch{hash='overview';}const [chapterId,nodeId]=hash.split('/');const focused=document.activeElement?.getAttribute('data-node');current=chapters.find(c=>c.id===chapterId)||chapters[0];selected=current.nodes.find(n=>n.id===nodeId)||current.nodes[0];render();if(focused&&current.nodes.some(n=>n.id===focused))$('diagram').querySelector(`[data-node="${focused}"]`)?.focus({preventScroll:true});}
  function go(chapterId,nodeId){const next='#'+chapterId+(nodeId?'/'+nodeId:'');if(location.hash===next)route();else location.hash=next;}
  function nav(){const nav=$('chapters');nav.replaceChildren();chapters.forEach(c=>{const btn=document.createElement('button');btn.className='nav-item';btn.setAttribute('aria-current',c.id===current.id?'step':'false');const count=c.nodes.filter(unresolved).length;btn.innerHTML=`<span class="nav-number">${esc(c.number)}</span><span>${esc(c.navLabel||c.title)}</span>${count?`<span class="nav-issue" title="Số bước còn cần xử lý">${count}</span>`:''}`;btn.addEventListener('click',()=>go(c.id));nav.append(btn);});}
  function graph(){
    const svg=$('diagram');svg.replaceChildren();const mobile=window.innerWidth<=650;const nodeWidth=mobile?290:220;const rows=mobile?current.nodes.length:Math.max(...current.nodes.map(n=>n.row))+1;const height=rows*130+32;svg.setAttribute('viewBox',`0 0 ${mobile?350:800} ${height}`);
    const defs=svgEl('defs');const marker=svgEl('marker',{id:'arrow',viewBox:'0 0 10 10',refX:9,refY:5,markerWidth:6,markerHeight:6,orient:'auto-start-reverse'});marker.append(svgEl('path',{d:'M 0 1 L 9 5 L 0 9',fill:'none',stroke:'var(--muted)','stroke-width':1.4}));defs.append(marker);svg.append(defs);
    const pos=new Map(current.nodes.map((n,i)=>[n.id,{x:mobile?30:30+n.col*260,y:20+(mobile?i:n.row)*130}]));
current.edges.forEach((edge,index)=>{const a=pos.get(edge.from),b=pos.get(edge.to);if(!a||!b)throw new Error('Invalid edge '+edge.from+' → '+edge.to);let d,lx,ly;if(mobile&&Math.abs(b.y-a.y)>130){const left=index%2===0;const port=left?30:320;const gutter=left?10:340;d=`M ${port} ${a.y+42} H ${gutter} V ${b.y+42} H ${port}`;lx=175;ly=a.y+106;}else if(a.y===b.y){const right=b.x>a.x;const ax=a.x+(right?nodeWidth:0),bx=b.x+(right?0:nodeWidth);d=`M ${ax} ${a.y+42} H ${bx}`;lx=(ax+bx)/2;ly=a.y+32;}else {const ax=a.x+nodeWidth/2,ay=a.y+84,bx=b.x+nodeWidth/2,by=b.y,mid=ay+(by-ay)/2;d=`M ${ax} ${ay} V ${mid} H ${bx} V ${by}`;lx=(ax+bx)/2;ly=mid-8;}if(mobile){const outgoing=current.edges.filter(e=>e.from===edge.from&&e.label);const rank=outgoing.indexOf(edge);lx=(rank+0.5)*350/Math.max(1,outgoing.length);ly=a.y+109;}svg.append(svgEl('path',{d,class:'edge'+(edge.dashed?' dashed':''),'marker-end':'url(#arrow)'}));if(edge.label){const w=edge.label.length*6+12;svg.append(svgEl('rect',{x:lx-w/2,y:ly-11,width:w,height:16,rx:3,class:'edge-label-bg'}));svg.append(svgEl('text',{x:lx,y:ly,'text-anchor':'middle',class:'edge-label'},edge.label));}});
    current.nodes.forEach(node=>{const {x,y}=pos.get(node.id);const group=svgEl('g',{class:`node ${node.status}${selected.id===node.id?' selected':''}${issuesOnly&&!unresolved(node)?' dim':''}`,transform:`translate(${x},${y})`,tabindex:0,role:'button','aria-label':`${node.title}. ${node.sub}. ${labels[node.status]}`,'aria-pressed':selected.id===node.id?'true':'false','data-node':node.id});group.append(svgEl('title',{},node.summary));group.append(svgEl('rect',{width:nodeWidth,height:84,rx:10}));group.append(svgEl('rect',{x:0,y:16,width:4,height:52,rx:2,class:'status-bar'}));const lines=words(node.title,mobile?30:23);lines.forEach((line,i)=>group.append(svgEl('text',{x:16,y:lines.length===1?34:27+i*19},line)));group.append(svgEl('text',{x:16,y:68,class:'node-sub'},node.sub));const activate=()=>{go(current.id,node.id);if(mobile)setTimeout(()=>$('detail').scrollIntoView({block:'start'}),30);};group.addEventListener('click',activate);group.addEventListener('keydown',ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();activate();}if(ev.key==='ArrowDown'||ev.key==='ArrowUp'){ev.preventDefault();const index=current.nodes.indexOf(node)+(ev.key==='ArrowDown'?1:-1);const next=current.nodes[index];if(next)svg.querySelector(`[data-node="${next.id}"]`).focus();}});svg.append(group);});
    $('graph-count').textContent=`${current.nodes.length} bước · ${current.nodes.filter(unresolved).length} bước còn cần xử lý`;
  }
  function details(){const n=selected;const outputs=Array.isArray(n.output)?n.output:[n.output];const action=n.href?`<a class="button detail-action" href="${esc(n.href)}">Mở bảng P0–P20 →</a>`:n.jump?`<button class="button detail-action" id="open-chapter">Mở quy trình chi tiết →</button>`:'';$('detail').innerHTML=`<span class="badge ${n.status}">${esc(labels[n.status])}</span><h2 id="detail-title">${esc(n.title)}</h2><p class="intro">${esc(n.summary)}</p>${action}<h3>Điều kiện & xử lý</h3><ul>${n.steps.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h3>Kết quả / dữ liệu thay đổi</h3>${outputs.map(x=>`<p>${esc(x)}</p>`).join('')}${n.issues.map(i=>`<article class="issue ${i.kind}"><h4>${esc(i.id)} · ${esc(i.title)}</h4><p>${esc(i.body)}</p><small><strong>${i.kind==='fixed'?'Đã cập nhật':'Cần làm'}:</strong> ${esc(i.next)}</small></article>`).join('')}<h3>Bằng chứng source</h3>${n.refs.map(key=>{const s=sources[key];return `<a class="source" href="../${esc(s[0])}" target="_blank" rel="noopener">${esc(s[0])}<span>${esc(s[1])}</span></a>`;}).join('')}<p class="source-note">Đọc code tại working tree ngày 24/09/2026. Link mở file source khi xem qua file:// hoặc server có repo root. Đây không phải kết quả kiểm thử runtime.</p>`;if(n.jump)$('open-chapter').addEventListener('click',()=>go(n.jump));}
  function render(){nav();$('chapter-title').textContent=current.title;$('chapter-number').textContent=current.id==='overview'?'TỔNG QUAN · BẮT ĐẦU TẠI ĐÂY':`GIAI ĐOẠN ${current.number}`;$('chapter-description').textContent=current.description;graph();details();}
  $('issues-toggle').addEventListener('click',()=>{issuesOnly=!issuesOnly;$('issues-toggle').setAttribute('aria-pressed',String(issuesOnly));graph();});
  $('search').addEventListener('input',()=>{const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').toLowerCase();const query=normalize($('search').value.trim());const box=$('results');box.replaceChildren();box.hidden=!query;if(!query)return;const matches=chapters.flatMap(c=>c.nodes.map(n=>({c,n}))).filter(({n})=>normalize([n.title,n.sub,n.summary,...n.steps,...n.issues.map(i=>i.id+' '+i.title+' '+i.body)].join(' ')).includes(query)).slice(0,12);if(!matches.length){box.textContent='Không tìm thấy. Thử “cọc”, “gia hạn”, “EXP01” hoặc “sai mã”.';return;}matches.forEach(({c,n})=>{const b=document.createElement('button');b.innerHTML=`${esc(n.title)}<small>${esc(c.title)}</small>`;b.addEventListener('click',()=>{go(c.id,n.id);box.hidden=true;$('search').value='';});box.append(b);});});
  $('search').addEventListener('keydown',e=>{if(e.key==='Escape')$('results').hidden=true;if(e.key==='ArrowDown'){$('results').querySelector('button')?.focus();}});
  document.addEventListener('click',e=>{if(!e.target.closest('.search-wrap'))$('results').hidden=true;});
  try{document.documentElement.dataset.theme=localStorage.getItem('homeland-lifecycle-theme')||'light';}catch{}
  $('theme').addEventListener('click',()=>{const theme=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=theme;try{localStorage.setItem('homeland-lifecycle-theme',theme);}catch{}});
  window.addEventListener('hashchange',route);window.addEventListener('resize',graph);route();
})();
