/* Planning only. No phase below is automatically marked implemented or accepted. */
(function(){
  'use strict';
  // Updated in-place as work moves. "doing" means code is being implemented
  // or verified; it never asserts UAT/release completion.
  const phaseUpdates={
    P31:['doing','23/09/2026 · ĐÃ CẬP NHẬT QUY TẮC CHỦ NHÀ','Không áp tỷ lệ hoàn/giữ/khấu trừ cố định: chủ nhà quyết mức hợp lý theo từng khách và tình huống. Hệ thống chỉ bắt buộc người vận hành nhập lý do, phân bổ đúng R + K + D = số dư cọc, chặn hủy nhầm hợp đồng ACTIVE và lưu chứng từ khi đánh dấu đã hoàn. Ảnh, ảnh chụp camera và PDF được tải qua kho tài liệu tenant; hoàn PENDING chỉ chuyển COMPLETED khi có chứng từ. Quyết toán trả phòng cũng đã bắt buộc chứng từ cho hoàn ngay hoặc hoàn tất phiếu chờ, và ghi proof vào receipt/audit/outbox. Còn xác định basis hoa hồng, template precedence và UAT kênh gửi thật.',['apps/api/src/deposits/deposit-core.policy.ts','apps/api/src/deposits/deposit-core.service.ts','apps/api/src/contracts/contracts.service.ts','apps/web/components/contracts/OperationsContractDrawer.tsx','apps/web/components/common/RefundProofUploader.tsx','apps/api/src/automation/rules/reminder-policy.ts'],['Không có policy % cố định: chủ nhà quyết từng case, nhưng lý do và R + K + D = số dư là invariant bắt buộc.','Guard fail-closed cho cọc giữ phòng đã gắn hợp đồng ACTIVE.','Chứng từ ảnh/camera/PDF cho hoàn cọc và quyết toán: hoàn COMPLETED hoặc hoàn tất PENDING bị chặn nếu thiếu proof; proof lưu receipt/audit/outbox.','Một reminder policy dùng chung thay cho ngưỡng hard-code trong registry.','Focused settlement 70/70, focused deposit core và web command, API/Web typecheck đã đạt.']],
    P32:['doing','23/09/2026 · ĐÃ XÁC MINH HOLD / REPLAY','Convert HĐ cọc → HĐ thuê vẫn là một transaction SERIALIZABLE cho HĐ DRAFT + cọc SECURITY, cặp key :contract/:deposit replay-safe và recovery draft legacy. Command nay đồng thời tạo invoice tiền thuê kỳ đầu DRAFT theo ENTRY key (chỉ phát hành khi activate); nếu thiếu cọc, tạo ngay PaymentRequest/QR cho đúng phần còn thiếu theo ledger, không thu lại phần cọc đã chuyển. Khi duyệt HĐ mới, room hold ACTIVE đã gắn với chính cọc SECURITY của HĐ được coi là reservation hợp lệ rồi chuyển CONVERTED theo CAS, nên không tự chặn HĐ của chính nó. Focused contract/deposit/payment 112/112, API/Web typecheck đã đạt. Còn E2E crash/webhook, DB concurrency và review tiền độc lập.',['apps/api/src/contracts/contracts.controller.ts','apps/api/src/contracts/contracts.service.ts','apps/api/src/contracts/contracts.module.ts','apps/api/src/deposits/deposit-core.service.ts','apps/api/src/payments/payments.service.ts','apps/api/src/contracts/contracts.service.spec.ts','apps/web/components/contracts/OperationsContractDrawer.tsx'],['Transaction SERIALIZABLE tạo HĐ thuê DRAFT, cọc SECURITY và liên kết canonical, có replay/recovery draft.','HĐ mới được phép duyệt với chính room hold của nó; hold chuyển CONVERTED bằng update CAS, foreign hold vẫn chặn.','Invoice ENTRY tiền thuê kỳ đầu được tạo DRAFT cùng lệnh; activate chỉ phát hành lại đúng invoice đó.','QR cọc bổ sung lấy phần thiếu theo ledger (B=2tr, C=5tr ⇒ QR 3tr); QR tiền thuê đầu kỳ được trả sau activate.','Focused contract/deposit/payment 112/112, API/Web typecheck đạt; chưa thay thế E2E, DB concurrency hay review tiền.']],
    P33:['doing','23/09/2026 · ĐÃ BỔ SUNG CHỨNG TỪ HOÀN','Hủy cọc giữ phòng nay nạp đúng hợp đồng liên kết: pre-active chuyển CANCELLED, ACTIVE bị chặn fail-closed. Chủ nhà tự chọn hoàn đủ/một phần/không hoàn, còn ledger luôn bắt R + K + D = balance và PENDING không là cash-out. Màn hình hoàn/hủy cọc có tải ảnh, chụp camera hoặc PDF; khi đánh dấu đã hoàn thì chứng từ bắt buộc, được lưu vào operation, audit và event thông báo. Focused deposit core 21/21, web command 18/18, API/Web typecheck đạt. Còn UAT upload/storage thật, delivery notification, đối soát phòng/roommate và Sol High review vùng tiền.',['apps/api/src/deposits/deposit-core.service.ts','apps/api/src/deposits/deposit-core.service.spec.ts','apps/api/src/deposits/deposits.dto.ts','apps/web/components/deposits/OperationsDepositDrawer.tsx','apps/web/components/contracts/OperationsContractDrawer.tsx','apps/web/components/common/RefundProofUploader.tsx'],['Hủy cọc pre-active đổi hợp đồng sang CANCELLED, không xóa lịch sử; ACTIVE bị chặn fail-closed bằng dữ liệu hợp đồng thực tế.','Chủ nhà chọn hoàn/giữ/khấu trừ từng case; invariant R + K + D = balance và refund PENDING không được coi là tiền đã chi.','Ảnh, camera và PDF được tải lên; hoàn COMPLETED và hoàn tất PENDING bắt buộc có chứng từ, lưu vào operation/audit/outbox.','Focused deposit core 21/21, web command 18/18, API/Web typecheck đã đạt.']],
    P34:['doing','23/09/2026 · ĐÃ KHÓA CẤN TIỀN TỪ QR','Invoice.pay tạo Payment + PaymentAllocation riêng theo provider/reference và CAS trên số dư. UI thu tiền mặt 2tr nay chỉ tạo MANUAL/CASH allocation; chọn QR không còn xác nhận thủ công mà mở QR theo phần còn nợ 3tr và chỉ webhook SePay mới ghi thu. Webhook không được tự cấn quá số tiền của PaymentRequest dù hóa đơn còn nợ; phần dư đi vào đối soát. Gán thủ công một phần cho invoice cọc chỉ ghi allocation invoice, không được collect toàn bộ BOOKING deposit cho đến khi invoice PAID. Focused contract/deposit/payment 112/112, API/Web typecheck đạt. Còn E2E concurrent/retry và finance review trước khi đóng.',['apps/api/src/invoices/invoices.service.ts','apps/api/src/payments/payments.service.ts','apps/api/src/payments/payments.service.spec.ts','apps/web/components/invoices/OperationsBillingDrawer.tsx'],['Payment + PaymentAllocation theo provider/reference, có CAS trên số dư invoice.','Thu tiền mặt chỉ ghi MANUAL/CASH; chọn QR chỉ mở mã theo số còn nợ và chờ webhook SePay.','Webhook chỉ cấn tối đa amount của PaymentRequest; dư tiền đi luồng đối soát.','Booking deposit chỉ collect khi hóa đơn cọc đã PAID, không ở lần gán partial.','Focused contract/deposit/payment 112/112, API/Web typecheck đạt; chưa thay thế E2E concurrent/retry hay review tiền.']],
    P35:['doing','23/09/2026 · ĐÃ BỔ SUNG TRACE HOÀN DƯ','Đã tách rõ duplicate kỹ thuật (provider transaction id) với giao dịch bank mới nhưng trùng memo/payment code: giao dịch thứ hai chuyển NEEDS_REVIEW, audit + cảnh báo admin, không allocation hoặc xác nhận khách lần hai. Webhook chỉ cấn tối đa số tiền của PaymentRequest; phần vượt không âm thầm trả vào hóa đơn mà phải resolution theo từng log. Chọn REFUND_PENDING tạo receipt PENDING và journal nhận tiền thừa; hoàn tất buộc có ảnh/camera/PDF, chuyển receipt COMPLETED và journal chi hoàn dưới advisory lock. API đối soát trả receipt, cả hai journal và tệp proof theo từng webhook; UI hiển thị mã chứng từ cùng số tệp đã lưu. Focused contract/deposit/payment/finance 133/133, API/Web typecheck đạt. Còn DB concurrency, staging provider và finance review.',['apps/api/src/payments/payments.service.ts','apps/api/src/payments/payments.service.spec.ts','apps/api/src/payments/payments.controller.ts','apps/api/src/finance/finance-reporting.service.ts','apps/api/src/finance/finance-reporting.service.spec.ts','apps/web/components/finance/SePayReconciliationSummary.tsx','apps/web/components/common/RefundProofUploader.tsx'],['Exact duplicate theo provider transaction id được idempotent; không allocation hoặc gửi xác nhận lần hai.','Giao dịch bank khác nhưng trùng memo/payment code chuyển NEEDS_REVIEW, có audit và cảnh báo admin.','Webhook chỉ cấn tối đa PaymentRequest; toàn bộ phần dư vẫn phải credit/carry-forward/refund theo log.','REFUND_PENDING tạo receipt và journal; hoàn tất cần ảnh/camera/PDF, có receipt COMPLETED + journal chi hoàn dưới advisory lock.','Đối soát trả receipt, pending/completed journal và tệp proof theo từng log; UI hiển thị trace đó.','Focused contract/deposit/payment/finance 133/133, API/Web typecheck đạt; còn DB concurrency, staging provider và review tiền.']],
    P36:['doing','23/09/2026 · ĐÃ KHÓA BIÊN NGÀY UTC+7','PaymentPromise độc lập với invoice ledger: chỉ hẹn khi còn nợ, hẹn mới supersede hẹn mở, thu đủ tự FULFILLED; scheduler đến hết ngày hẹn chuyển OVERDUE, nhắc khách/admin và tạo task. Cron và mọi khoảng ngày nhắc hóa đơn/quá hạn/hết hạn/hẹn trả nay cố định `Asia/Ho_Chi_Minh`, không phụ thuộc timezone máy chủ. Drawer hóa đơn nay xem/lập/đổi hẹn với idempotency, hiển thị trạng thái và nhắc rõ hẹn không phải tiền đã thu. Registry dùng tenant threshold thay vì cứng 3/7/30. SQL migration đã chạy thành công trên clone schema database tạm và database tạm đã xóa; database vận hành không bị apply. Còn provider delivery/UAT, kiểm thử scheduler staging và review tiền độc lập.',['packages/database/prisma/migrations/20260923100000_add_payment_promises/migration.sql','apps/api/src/invoices/invoices.service.ts','apps/api/src/invoices/invoices.service.spec.ts','apps/api/src/automation/rules/rule.scheduler.ts','apps/api/src/automation/rules/rule.scheduler.spec.ts','apps/web/components/invoices/OperationsBillingDrawer.tsx','apps/web/lib/api/invoices.api.ts'],['PaymentPromise tách khỏi ledger: chỉ lập khi còn nợ, hẹn mới supersede hẹn cũ, thu đủ tự FULFILLED.','Scheduler quét hết ngày hẹn, chuyển OVERDUE, nhắc khách/admin và tạo task.','Cron và các biên ngày due-soon, overdue, hết hạn hợp đồng, hẹn trả đều dùng Asia/Ho_Chi_Minh; có regression khi worker chạy UTC.','Drawer hóa đơn đã xem/lập/đổi hẹn idempotent, hiển thị rõ hẹn không phải tiền đã thu.','Migration PaymentPromise đã verify thành công trên bản sao schema cô lập; không apply database vận hành.','Focused scheduler 6/6, API và Web typecheck đã đạt.']],
    P37:['blocked','23/09/2026 · CHỜ P31–P36 ĐÓNG','Code mẫu tin đã được chuẩn bị nhưng bị đóng băng khỏi thứ tự thực thi: P31–P36 còn review tiền, concurrency/staging, migration và UAT chưa đủ điều kiện đóng. Card này không được coi là phase đang triển khai hoặc được nghiệm thu; chỉ mở lại sau khi P31–P36 có evidence tương ứng.',['apps/api/src/communication/templates/notification-template-catalog.ts','apps/api/src/communication/templates/template.engine.ts','apps/api/src/communication/communication.service.ts','apps/api/src/communication/communication.controller.ts','apps/api/src/communication/providers/communication.providers.ts','apps/web/components/settings/sections/SettingsNotificationAutomation.tsx','packages/database/prisma/migrations/20260923113000_add_notification_template_versions/migration.sql'],['Code chuẩn bị có catalog, editor, draft/publish/rollback và snapshot retry.','Không dùng code/test focused để thay thế migration, provider UAT hoặc gate P31–P36.']],
    P38:['blocked','23/09/2026 · CHỜ P31–P36 ĐÓNG','Code reliability queue đã được chuẩn bị nhưng bị đóng băng khỏi thứ tự thực thi. P38 chỉ được mở sau P33/P35/P37 theo dependency; hiện ưu tiên trả các điều kiện đóng P31–P36 thay vì cộng thêm scope notification.',['apps/api/src/communication/communication.service.ts','apps/api/src/communication/communication.service.spec.ts','apps/api/src/communication/communication.scheduler.ts','apps/api/src/automation/automation.listener.ts'],['No-provider có delivery FAILED và aggregate không báo DELIVERED giả.','Chưa nghiệm thu idempotency/event, crash recovery hay provider thật.']],
    P40:['doing','23/09/2026 · ĐÃ NỐI LỊCH SỬ SỔ CÁI THEO KỲ','Biểu đồ Báo cáo không còn lấy tổng tiền thuê của hợp đồng ACTIVE để điền vào tháng không có journal, cũng không còn gán profit = revenue. Lịch sử nay đi qua FinanceReporting với period rõ (`months` 1–24, `year`, `month` kết thúc), chỉ dùng journal POSTED/REVERSED và tiếp tục loại cọc khỏi doanh thu. UI gọi `/finance/profit-loss-history`; route Dashboard cũ cũng ủy quyền cùng nguồn. Focused finance/dashboard 24/24, API/Web typecheck và web lint đạt. Còn drill-down, đối soát độc lập và UAT dữ liệu thật.',['apps/api/src/finance/finance-reporting.service.ts','apps/api/src/finance/finance-reporting.service.spec.ts','apps/api/src/finance/finance.controller.ts','apps/api/src/dashboard/dashboard.service.ts','apps/api/src/dashboard/dashboard.service.spec.ts','apps/web/lib/api/reports.api.ts','apps/web/lib/queries/reports.queries.ts','apps/web/app/reports/page.tsx'],['Biểu đồ được gắn nhãn sổ cái không còn trình bày rent dự kiến là doanh thu/lợi nhuận.','Period contract 1–24 tháng có tenant scope, POSTED/REVERSED và loại cọc theo FinanceReporting.','Focused finance/dashboard 24/24, API/Web typecheck và web lint đã đạt.']],
    P43:['doing','23/09/2026 · ĐÃ KHÓA RETRY AI PERSISTED','Mỗi gửi chat AI nay bắt buộc `Idempotency-Key` UUID. State machine `RUNNING → PROVIDER_COMPLETED → COMPLETED/FAILED` được lưu bền theo tenant/user/key, có request hash, lease reclaim và kết quả provider được ghi trước khi transaction tạo cặp message. Retry completed chỉ replay kết quả; request đang chạy không gọi provider lần hai; retry FAILED cùng nội dung mới reclaim. UI giữ đúng key khi gửi lại nguyên câu và đổi key khi người dùng sửa nội dung. Migration chỉ được thêm vào repo, chưa apply database vận hành. Focused AI 9/9, Prisma validate, API/Web typecheck và web lint đạt. Còn staging migration/concurrency, RAG/trích xuất thật và review quyền consumer.',['apps/api/src/ai/ai.controller.ts','apps/api/src/ai/ai.controller.spec.ts','apps/web/components/ai/AiCommandCenter.tsx','apps/web/lib/api/ai.api.ts','apps/web/lib/queries/ai.queries.ts','packages/database/prisma/schema.prisma','packages/database/prisma/migrations/20260923140000_add_ai_chat_requests/migration.sql'],['Chat retry có state DB, hash mismatch bị chặn, RUNNING không gọi provider lần hai, COMPLETED replay kết quả và PROVIDER_COMPLETED không tính token/provider lần nữa.','Cặp user/assistant cùng chuyển COMPLETED trong transaction; retry FAILED cùng nội dung được reclaim.','Focused AI 9/9, Prisma validate, API/Web typecheck và web lint đã đạt; migration chưa được apply.']],
  };
  // Estimates combine implemented code, focused verification and outstanding
  // acceptance work. They are deliberately not release or UAT percentages.
  const phaseProgress={
    P31:[75,'Core policy guard, evidence và focused test đã có; còn owner/FIN/OPS chốt vận hành, template precedence và UAT gửi thật.'],
    P32:[85,'Đã có transaction chuyển cọc, HĐ thuê, invoice ENTRY, QR, replay legacy và consume own hold; còn crash/webhook E2E, DB concurrency cùng review tiền độc lập.'],
    P33:[80,'Đã có cancel/refund ledger, chứng từ và guard ACTIVE; còn UAT storage/notification, roommate và review tiền.'],
    P34:[80,'Đã tách cash/QR và allocation, chặn partial cọc bị collect đủ; còn kiểm thử concurrent/retry trên môi trường tích hợp và finance review.'],
    P35:[84,'Đã phân loại duplicate, review, manual assign, receipt/journal/proof có trace đối soát và lock hoàn tiền; còn DB concurrency, staging provider và finance review.'],
    P36:[80,'Đã có PaymentPromise, scheduler UTC+7, UI và migration verify cô lập; còn provider delivery, scheduler staging/UAT và finance review.'],
    P37:[0,'Bị khóa theo thứ tự. Code chuẩn bị trước đó không được tính là tiến độ thực thi cho đến khi P31–P36 đóng bằng evidence thật.'],
    P38:[0,'Bị khóa theo dependency P33/P35/P37. Code chuẩn bị trước đó không được tính là tiến độ thực thi; ưu tiên P31–P36.'],
    P39:[10,'Có query invalidation cục bộ; chưa có tenant realtime, reconnect/resync và multi-instance broker.'],
    P40:[43,'FinanceReporting có nền dữ liệu thật; Analytics occupancy nay đếm phòng tenant-scoped thật (active/OCCUPIED/AVAILABLE/MAINTENANCE), debt analytics dùng getDebtSummary tenant-scoped với top debtor không lộ ID/phone và collectionRate=null khi thiếu denominator. Cache debt được invalidation cùng finance/revenue. Các endpoint analytics revenue/finance mẫu nay fail-closed (không trả số lợi nhuận/chi phí/doanh thu giả) cho đến khi có FinanceReporting period contract; focused analytics/cache 6/6 và API typecheck đạt. PDF report placeholder cũng fail-closed với REPORT_PDF_EXPORT_UNAVAILABLE thay vì gửi byte text mang MIME application/pdf (focused 1/1, API typecheck đạt). Lịch sử Reports nay dùng `/finance/profit-loss-history` period-scoped (1–24 tháng) từ FinanceReporting, kế thừa POSTED/REVERSED và loại cọc; Dashboard route cũ ủy quyền cùng nguồn, nên không còn fallback tiền thuê ACTIVE hoặc profit = revenue khi sổ cái trống (finance/dashboard 24/24, API/Web typecheck và web lint đạt). Reports vẫn cần drill-down, đối soát tiền độc lập và UAT dữ liệu thật; chưa đủ điều kiện review tài chính để đóng P40.'],
    P41:[5,'Chưa có CommissionPolicy, basis/share, approval/payout hay clawback.'],
    P42:[87,'Task board, Operations Insights, Sales summary, Tenant Grid server pagination, tạo Lead, chuyển stage Pipeline, form Thêm khách thuê và Room Filters đều dùng dữ liệu tenant thật. Operations Sales Insights đã bỏ các số Facebook/TikTok/KPI nhân sự hard-code; chỉ hiển thị stale/active/proposal/won từ summary tenant-scoped, loading/error/empty không suy diễn số liệu (focused 3/3, web typecheck/lint đạt). Insights Task cũng chỉ hiển thị metrics có nguồn; đổi trạng thái Task nay dùng compare-and-set để không ghi đè thao tác đồng thời (Tasks 7/7). Bộ lọc Sales chỉ còn tìm kiếm/trạng thái/sắp xếp có contract; truyền query vào API và giữ metadata phân trang server thay vì đồng nhất tổng với số item đang tải (web 4/4, typecheck/lint đạt). Sales create/stage và Customer create dùng idempotency replay/conflict + audit transaction tenant-scoped; KPI/Funnel không còn list cap 100; grid dùng meta.total, hợp đồng/phòng trực tiếp theo khách và room filters gửi đủ building/floor/status/type (Sales create 4/4, Sales stage 4/4, Customer 17/17 + web 2/2, Room filters 3/3). Còn staging concurrency, Sales convert/import, CRM journey E2E và E2E browser Tenant Grid chờ credential.'],
    P43:[85,'AI ingest thiếu text extraction đã fail-closed; Command Center dùng lịch sử hội thoại nguồn thật; AI controller kiểm tra ownership, lấy history server-side, chỉ lưu một cặp user/assistant và từ chối final role không phải user. Chat retry nay có state DB tenant/user/key `RUNNING → PROVIDER_COMPLETED → COMPLETED/FAILED`, hash mismatch bị chặn, result provider được lưu trước transaction message và COMPLETED replay không gọi provider lần hai (AI 9/9, schema validate, API/Web typecheck và web lint đạt; migration chưa apply). Thẻ RAG không còn ngụ ý hợp đồng/hóa đơn đã index: nguồn tri thức tenant hiện ghi rõ chưa kết nối cho đến khi có API nguồn thật. AI draft không còn cho nút duyệt giả: chưa có command nghiệp vụ thì nút bị disabled, chỉ có đóng card hoạt động (regression + web typecheck/lint đạt). Documents tải có Bearer auth + storage tenant gate; catalog template tenant và modal tạo PDF thật validate JSON, báo lỗi rõ, refresh danh sách sau thành công. Upload tenant-owned chỉ nhận PDF/ảnh tối đa 20 MB; backend allowlist MIME và size trước khi ghi, upload fail không trả success. Nếu lưu metadata thất bại sau khi ghi tệp, tệp mồ côi được xóa và vẫn trả lỗi gốc (documents focused 15/15, API typecheck đạt). Regression desktop cover image/PDF/camera, chặn >20 MB/tệp sai loại, upload fail và chỉ refresh khi success (eslint + diff check đạt; chưa có credential để chạy E2E). Backend chỉ success sau Document OTHER/DRAFT, DocumentVersion tenant-owned và currentVersionId. Manual Workflow/Rule lấy tenant từ phiên đăng nhập, execution detail/list tenant-scoped, trả executionId+status thật; UI chỉ báo success khi SUCCESS, hiển thị RUNNING và poll giới hạn, FAILED thành lỗi (API 30/30, web 2/2). Còn E2E staging, migration AI, RAG/trích xuất thật và review quyền consumer.'],
    P44:[0,'Chờ các phase phụ thuộc, E2E, UAT provider, evidence và ký FIN/OPS/owner.'],
    P45:[0,'Chỉ bắt đầu sau P44 và evidence production được ủy quyền riêng.'],
  };
  const phases=[
    ['P31','Chốt policy và invariant',['P0','P1'],['DEV / FIN / OPS'],'Chốt trạng thái HĐ cọc khi chuyển/hủy; chủ nhà quyết hoàn/giữ/khấu trừ theo từng ca (không có % cố định); cọc không là doanh thu; %/basis hoa hồng; ngày hẹn; template precedence và SLO realtime.','Biên bản vận hành xác nhận quyền quyết định từng case của chủ nhà; ma trận B<C/B=C/B>C và R+K+D=B; lý do/chứng từ hoàn được lưu; không tự gán % hoa hồng.','maps/LIFECYCLE_LOGIC.md'],
    ['P32','Chuyển cọc + HĐ thuê mới',['P31','P3','P4'],['backend-core-fixer'],'Nối createRentalFromBookingHold với convertToSecurity; thu thêm max(C−B,0), tách tiền thuê; cọc dư CREDIT/REFUND; giữ chứng từ cũ, một liên kết canonical.','Replay/double click/crash giữa bước không tạo HĐ/cọc/QR trùng; B<C/B=C/B>C đúng; Sol High review trước gate tiền.','apps/api/src/deposits/deposit-core.service.ts','apps/api/src/contracts/contracts.service.ts'],
    ['P33','Hủy giữ phòng và hoàn tiền',['P31','P7'],['backend-core-fixer'],'Chủ nhà chọn hoàn đủ/một phần/không hoàn theo từng case; tách pending và chi thật; liên kết trạng thái HĐ cọc/pre-active, không tự hủy ACTIVE; tính lại hold/room theo occupancy còn lại.','Không hoàn vượt balance; pending chưa cash-out; complete idempotent; không giải phóng roommate/hold khác; audit + chứng từ ảnh/camera/PDF.','apps/api/src/deposits/deposit-core.policy.ts','apps/api/src/deposits/deposit-core.service.ts','apps/web/components/common/RefundProofUploader.tsx'],
    ['P34','Thanh toán tiền mặt + QR',['P32','P6'],['backend-core-fixer'],'Mỗi lần nhận một Payment/reference và allocation; QR theo số dư, xử lý QR cũ và overpay; partial không sửa nghĩa vụ gốc.','Ví dụ 5tr = cash 2tr + QR 3tr, nhận đồng thời/retry đúng 5tr; credit/refund phần dư; tenant isolation và không double ledger.','apps/api/src/invoices/invoices.service.ts','apps/api/src/payments/payments.service.ts'],
    ['P35','Chuyển khoản hộ / sai nội dung / giao dịch trùng',['P34'],['integration-fixer'],'Unmatched → review → manual assign với bank reference/owner/tenant; lưu người chuyển hộ và lý do gán; chỉ báo khách sau phân bổ đã commit. Tách rõ duplicate webhook hoặc cùng providerRef (bỏ qua, link bản gốc, không allocation lần hai) với hai giao dịch ngân hàng khác nhau nhưng trùng nội dung/mã thanh toán (NEEDS_REVIEW, không tự gộp theo memo). Nếu giao dịch thứ hai là tiền thật thì xử lý như overpayment/credit/refund theo policy, không xóa hoặc giả lập duplicate.','Exact duplicate không nhận hai lần; cùng nội dung nhưng khác bank reference không tự assign; sai bank/tenant không gán; lock/CAS + unique provider reference/event id; admin nhận cảnh báo duplicate; khách chỉ nhận thông báo sau allocation canonical commit; duplicate thật không gửi “đã thanh toán” lần hai; overpayment thật gửi hướng xử lý credit/refund; hoàn tác/review có audit; Sol High review và gate tiền P32–P35 trước downstream.','apps/api/src/payments/payments.service.ts','apps/api/src/payments/payments.controller.ts','apps/api/src/finance/ledger.service.ts'],
    ['P36','Hẹn trả và hợp đồng sắp hết hạn',['P31','P13','P14','P34'],['backend-core-fixer'],'Đồng nhất ngưỡng config và rule 3/7/30; lưu hẹn trả; kiểm tra dư nợ lúc gửi; paid dừng nhắc; gia hạn hoặc preview settlement; nối tác vụ tạm trú còn thiếu ở P14.','Ngày hẹn khác dueDate; không nhắc số nợ cũ; renew/no-renew tạo đúng task/event, timezone và lịch sử không mất.','apps/api/src/automation/rules/rule.registry.ts','apps/api/src/contracts/contracts.service.ts'],
    ['P37','Settings: mẫu tin theo event/kênh',['P31','P36'],['frontend-fixer → integration-fixer (tuần tự)'],'Editor biến, preview, publish/version/rollback; tenant template ưu tiên default; rà override QR cả dispatch/dispatchDirect; Email/Telegram/Zalo escape đúng.','Mẫu Xin chào KH {{customerName}}…Xin cảm ơn render đủ biến; thiếu biến bị chặn; test gửi có người nhận rõ; snapshot nội dung/version giữ khi retry.','apps/api/src/communication/communication.service.ts','apps/api/src/communication/templates/template.engine.ts','apps/web/components/settings/sections/SettingsNotificationAutomation.tsx','packages/database/prisma/migrations/20260923113000_add_notification_template_versions/migration.sql'],
    ['P38','Event / queue / delivery đáng tin',['P33','P35','P37'],['integration-fixer'],'Nối invoice.overdue; audit thật; loại success giả SMS/Push; dedupe event/recipient/channel, crash recovery, retry/dead-letter và trạng thái provider accepted.','Lỗi một kênh không chặn kênh khác hoặc rollback tiền; replay không gửi trùng; PENDING refund không gửi “đã hoàn”; kiểm thử worker crash.','apps/api/src/automation/automation.listener.ts','apps/api/src/communication/communication.service.ts'],
    ['P39','Realtime đồng bộ các màn hình',['P35','P38','P5'],['frontend-fixer → integration-fixer (tuần tự)'],'Domain event tenant-scoped sau commit, invalidate Popup/Invoice/Deposit/Contract/Finance/history; broker đa instance; replay/resync sau reconnect, polling fallback.','Hai tab/hai tenant, disconnect, duplicate/out-of-order: mọi màn hình khớp DB; đo commit→UI riêng commit→provider, không tuyên bố zero-delay.','apps/web/lib/queries/payments.queries.ts','apps/api/src/communication/communication.controller.ts'],
    ['P40','Báo cáo doanh thu / chi phí',['P34','P16'],['backend-core-fixer → frontend-fixer (tuần tự)'],'FinanceReporting authoritative; tách revenue/cash/liability; bỏ Analytics demo và cap reports 500; PDF thật hoặc fail rõ; drill-down cùng filter scope.','Đối soát invoice/allocation/journal/receipt trên >500 records; cọc không cộng doanh thu; POSTED/REVERSED và owner isolation đúng; review tài chính.','apps/api/src/finance/finance-reporting.service.ts','apps/api/src/analytics/analytics.service.ts','apps/web/app/reports/page.tsx'],
    ['P41','Hoa hồng Sales / cấu hình %',['P31','P40'],['backend-core-fixer'],'CommissionPolicy phiên bản + attribution/share; tính basis hợp lệ, accrued→approved→paid; refund reversal/clawback; nối chi phí/chứng từ và phân quyền.','% do owner duyệt; share=100%; partial thu theo basis đã chọn; không double expense giữa accrual và payout; idempotency/tenant + Sol High review.','maps/LIFECYCLE_LOGIC.md','apps/api/src/sales/sales.service.ts'],
    ['P42','CRM / Tasks / các màn hình còn treo',['P32','P36','P41'],['frontend-fixer → backend-core-fixer (tuần tự)'],'Sales create/update/convert command; nút Thêm Lead/Import theo scope đã chốt; Task board dữ liệu thật; pagination KPI/Funnel/tenants thay cap tĩnh.','Lead convert chỉ sinh một chuỗi khách/cọc/HĐ; KPI theo toàn scope; task khai báo tạm trú và nhắc việc có chủ sở hữu, deadline, trạng thái.','apps/api/src/sales/sales.controller.ts','apps/web/components/tasks/OperationsBoard.tsx'],
    ['P43','Khóa placeholder và code thừa',['P37','P40','P42'],['writer theo từng module; tối đa một writer'],'AI tools dùng dữ liệu tenant hoặc tắt rõ; RAG đọc file; nối Documents/generation/signature; rà quyền file, workflow manual run; review consumer trước loại ledger/FinanceListener/JobDispatcher; report cron không log thành công giả.','Đường chưa hỗ trợ không trả success/demo; source ownership/tenant có test; no-consumer có danh mục; không xoá code chỉ vì diagram thiếu cạnh.','apps/api/src/ai/knowledge.service.ts','apps/api/src/documents/documents.service.ts','apps/api/src/automation/automation.controller.ts'],
    ['P44','Gate regression / integration / UAT',['P39','P40','P41','P42','P43','P17','P18','P30'],['milestone-reviewer → gate-tester'],'Nghiệm thu toàn hành trình booking/direct/convert/cancel/mixed/refund/renew; Hunonic 3 phòng × 3 kỳ; notification provider thật; chụp đủ 11 ảnh và chứng từ đối soát.','Sol High PASS vùng tiền/tenant/concurrency; tests và build đúng SHA, không biến skipped/mock thành pass; FIN/OPS/owner ký; phạm vi mới được phê duyệt.','docs/operations/GO_LIVE_TODO.md'],
    ['P45','Preflight / cutover / theo dõi',['P44','P19','P20'],['TL / OPS / FIN / OWNER'],'Đối chiếu critical path hiện hữu, off-host backup/restore, rollback, immutable SHA, monitor payment/outbox/notification; chỉ mở traffic sau sign-off.','Không dùng các phase mới để bỏ qua CORE-10/UAT/REL; production cần ủy quyền riêng; không migration/apply từ maps.','docs/operations/GO_LIVE_TODO.md']
  ];
  const section=document.createElement('section');section.id='next-phases';section.className='section';section.style.scrollMarginTop='90px';
  const title=document.createElement('h2');title.textContent='Các phase sửa tiếp theo — P31 → P45';
  const intro=document.createElement('p');intro.textContent='Kế hoạch mới sau rà soát 23/09/2026. P31–P36 bên dưới được cập nhật ngay khi có thay đổi code/test; "Đang thực hiện" không đồng nghĩa UAT hoặc go-live đã hoàn tất. Không đổi trạng thái CORE/UAT/REL. Phụ thuộc P31 trở đi là thứ tự triển khai. P44/P45 hội tụ nghiệm thu cũ và mới trước release.';
  const progressNote=document.createElement('p');progressNote.className='phase-progress-note';progressNote.textContent='Phần trăm là ước lượng tiến độ kỹ thuật: mã nguồn + kiểm thử focused + phần nghiệm thu đã có bằng chứng. UAT, review tài chính, migration và provider thật chỉ được tính khi có evidence; 100% mới được đánh xanh toàn card.';
  section.append(title,intro,progressNote);
  const flow=document.createElement('div');flow.className='note';flow.textContent='P31 policy → P32–P35 tiền/cọc → P36–P38 nhắc & mẫu tin & queue → P39 realtime. Song song về phụ thuộc: P40 báo cáo → P41 hoa hồng → P42 CRM → P43 phần còn lại. Hội tụ P44 gate → P45 release. Thực thi vẫn tối đa một writer theo AGENTS.md.';section.append(flow);
  const list=document.createElement('div');list.className='todo-list';
  phases.forEach(([id,name,deps,roles,scope,dod,...sources])=>{
    const card=document.createElement('article');card.className='box';card.id='work-'+id.toLowerCase();card.style.scrollMarginTop='90px';
    const update=phaseUpdates[id] || ['todo','CHƯA TRIỂN KHAI','Chưa có thay đổi code hoặc evidence mới trong lượt này.',[]];
    const label={done:'ĐÃ HOÀN THÀNH',doing:'ĐANG THỰC HIỆN',todo:'CHƯA TRIỂN KHAI',blocked:'BỊ CHẶN'}[update[0]];
    const badge=document.createElement('span');badge.className='pill '+update[0];badge.textContent=id+' · '+label;
    const h=document.createElement('h3');h.textContent=name;h.style.marginTop='12px';
    const [percent,percentReason]=phaseProgress[id] || [0,'Chưa có ước lượng tiến độ.'];
    const meter=document.createElement('div');meter.className='phase-progress '+update[0];
    const meterHeader=document.createElement('div');meterHeader.className='phase-progress-header';
    const meterLabel=document.createElement('span');meterLabel.textContent='Tiến độ ước lượng';
    const meterValue=document.createElement('strong');meterValue.textContent=percent+'%';
    meterHeader.append(meterLabel,meterValue);
    const meterTrack=document.createElement('div');meterTrack.className='phase-progress-track';meterTrack.setAttribute('role','progressbar');meterTrack.setAttribute('aria-label','Tiến độ '+id);meterTrack.setAttribute('aria-valuemin','0');meterTrack.setAttribute('aria-valuemax','100');meterTrack.setAttribute('aria-valuenow',String(percent));
    const meterFill=document.createElement('div');meterFill.className='phase-progress-fill';meterFill.style.width=percent+'%';meterTrack.append(meterFill);
    const meterReason=document.createElement('p');meterReason.className='phase-progress-reason';meterReason.textContent=percentReason;
    meter.append(meterHeader,meterTrack,meterReason);
    const dependency=document.createElement('p');dependency.append('Phụ thuộc: ');deps.forEach((dep,i)=>{if(i)dependency.append(', ');const link=document.createElement('a');link.href='#work-'+dep.toLowerCase();link.textContent=dep;link.onclick=()=>{const filter=document.getElementById('work-status');const search=document.getElementById('work-search');filter.value='all';search.value='';filter.dispatchEvent(new Event('change'));};dependency.append(link);});
    const body=document.createElement('p');body.textContent=scope;body.style.marginTop='10px';
    const acceptance=document.createElement('p');acceptance.style.marginTop='10px';const strong=document.createElement('strong');strong.textContent='Điều kiện đóng: ';acceptance.append(strong,dod);
    const owner=document.createElement('p');owner.textContent='Role đề xuất: '+roles.join(', ');owner.style.marginTop='10px';
    const paths=document.createElement('details');const summary=document.createElement('summary');summary.textContent='Code / tài liệu cần sửa';paths.append(summary);sources.forEach(src=>{const p=document.createElement('p');p.style.overflowWrap='anywhere';const link=document.createElement('a');link.href='../'+src;link.textContent=src;p.append(link);paths.append(p);});
    const progress=document.createElement('div');progress.className='todo-status '+update[0];
    const progressHeading=document.createElement('strong');progressHeading.textContent='Tiến độ · '+update[1];
    const progressNote=document.createElement('p');progressNote.textContent=update[2];progress.append(progressHeading,progressNote);
    if(update[3].length){const evidence=document.createElement('p');evidence.style.overflowWrap='anywhere';evidence.append('Đã chạm: ');update[3].forEach((src,index)=>{if(index)evidence.append(' · ');const link=document.createElement('a');link.href='../'+src;link.textContent=src; evidence.append(link);});progress.append(evidence);}
    card.dataset.workStatus=update[0];card.append(badge,h,meter,progress);
    if(update[4] && update[4].length){
      const completed=document.createElement('div');completed.className='todo-status done';
      const completedHeading=document.createElement('strong');completedHeading.textContent='ĐÃ XONG CODE + KIỂM THỬ FOCUSED';
      const completedList=document.createElement('ul');update[4].forEach(item=>{const row=document.createElement('li');row.textContent=item;completedList.append(row);});
      completed.append(completedHeading,completedList);card.append(completed);
    }
    card.append(dependency,body,acceptance,owner,paths);list.append(card);
  });section.append(list);document.querySelector('main').append(section);
  const review=document.createElement('section');review.className='section';review.id='phase-review-summary';
  const heading=document.createElement('h2');heading.textContent='Rà soát lại P0–P30 · 23/09/2026';
  const note=document.createElement('p');note.textContent='P2 giữ DONE; P15 cập nhật DONE phạm vi core theo GATE-09 đã ghi nhận trong TODO. Các phase còn lại giữ phần nghiệm thu còn mở. P27 giữ evidence UI delta đã có; P13 đã đồng nhất setting/registry/scheduler và biên ngày UTC+7. Rà soát tĩnh + evidence lịch sử, không chạy lại test nghiệp vụ/staging trong lượt này.';
  const counts={done:0,doing:0,blocked:0};window.HOMELAND_PHASE_REVIEW.entries.forEach(e=>counts[e[1]]++);
  const count=document.createElement('p');count.textContent=counts.done+' hoàn thành phạm vi · '+counts.doing+' đang thực hiện · '+counts.blocked+' bị chặn. Phần sửa code đã có không đồng nghĩa toàn phase được nghiệm thu.';
  review.append(heading,note,count);section.before(review);
  const shortcut=document.createElement('button');shortcut.className='cg-shortcut';shortcut.textContent='Phase tiếp theo ↓';shortcut.onclick=()=>section.scrollIntoView({block:'start'});document.querySelector('.toolbar').insertBefore(shortcut,document.getElementById('search'));
})();
